name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Geode CLI
        uses: geode-sdk/geode-build-action@main
        id: build

      - name: Upload .geode artifact
        uses: actions/upload-artifact@v4
        with:
          name: AIArchitect
          path: ${{ steps.build.outputs.build-output }}
